### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by pavelkryukov** [alexseppar/RISC-V-fsim#5]
MIPT-ILab maintains [MIPT-MIPS cycle-accurate simulator](https://github.com/MIPT-ILab/mipt-mips), and it has some pretty features:
* configurable models of branch prediction, data bypasses, instruction cache
* ELF loader
* interactive simulation driven by GDB
* support of MARS system calls and interface to add different system calls

That's all comes with
* 2 MHz idle simulation frequency
* 93% unit tests coverage in continuous integration
* More or less qualified documentation

The architecture of simulation is quite independent from ISA, and we are seriously looking to support RISC-V. Actually, we need only:
* a decoding unit
* a mapping of RISC-V instructions to our execution routines designed for MIPS or new ones
* test suites

... but we do not have human resources even for that. Our strategy is to assign feature implementations to 2nd year MIPT students, and their experience, expertise, and motivation is not quite sufficient for building RISC-V decoding from scratch.

Therefore, we would like to use some of your code. The question is licensing (MIPT-MIPS is [MIT licensed](https://github.com/MIPT-ILab/mipt-mips/blob/master/license.md) and cannot use GNU GPL code), and I could not find license information for your source code.

**Comment by kachkov98** [comment]
MIT license added

**Comment by pavelkryukov** [comment]
Thanks!
